name: Android CI

on:
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Apply Imibiyum changes
        run: unzip -o imibiyum-degisenler.zip

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Get LTW
        run: |
          mkdir -p app_pojavlauncher/libs
          cd app_pojavlauncher/libs
          wget https://github.com/PojavLauncherTeam/LTW/releases/latest/download/ltw-release.aar

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.11"

      - name: Build JRE JAR files
        run: |
          ./scripts/languagelist_updater.sh
          mkdir out
          gradle :jre_lwjgl3glfw:build --no-daemon

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug .apk (without bundled runtime)
        run: |
          gradle :app_pojavlauncher:assembleDebug
          mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/imibiyum-launcher.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: imibiyum-launcher
          path: out/imibiyum-launcher.apk
